name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test-build:
    env:
      DOTNET_NOLOGO: 'true'
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            5.x
            6.x
            7.x
      - name: Restore dependencies
        run: dotnet restore ./src/Serilog.Sinks.Console.LogThemes/Serilog.Sinks.Console.LogThemes.csproj
      - name: Build
        run: dotnet build ./src/Serilog.Sinks.Console.LogThemes/Serilog.Sinks.Console.LogThemes.csproj --no-restore
      - name: Run tests
        run: dotnet test /p:Configuration=Release --no-restore --no-build --verbosity normal

